// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Loan struct {
	ID                   string  `json:"id"`
	ContactID            int32   `json:"contactId"`
	LoanReference        string  `json:"loanReference"`
	LoanType             string  `json:"loanType"`
	InterestType         string  `json:"interestType"`
	PrincipalAmount      float64 `json:"principalAmount"`
	OutstandingPrincipal float64 `json:"outstandingPrincipal"`
	InterestRate         float64 `json:"interestRate"`
}

type Mutation struct {
}

type NewLoan struct {
	ContactID            int32   `json:"contactId"`
	LoanReference        string  `json:"loanReference"`
	LoanType             string  `json:"loanType"`
	InterestType         string  `json:"interestType"`
	PrincipalAmount      float64 `json:"principalAmount"`
	OutstandingPrincipal float64 `json:"outstandingPrincipal"`
	InterestRate         float64 `json:"interestRate"`
	InterestFrequency    string  `json:"interestFrequency"`
	LoanDate             string  `json:"loanDate"`
}

type Query struct {
}
