package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"
	"finance-tracker/backend/entities"
	"finance-tracker/backend/graph/model"
	"finance-tracker/backend/postgres"
	"strconv"
	"time"
)

// CreateLoan is the resolver for the createLoan field.
func (r *mutationResolver) CreateLoan(ctx context.Context, input model.NewLoan) (*model.Loan, error) {
	loanDate, err := time.Parse("2006-01-02", input.LoanDate)
	if err != nil {
		return nil, err
	}
	loan := entities.Loan{
		ContactID:            int(input.ContactID),
		LoanReference:        input.LoanReference,
		LoanType:             input.LoanType,
		InterestType:         input.InterestType,
		PrincipalAmount:      input.PrincipalAmount,
		OutstandingPrincipal: input.OutstandingPrincipal,
		InterestRate:         input.InterestRate,
		InterestFrequency:    input.InterestFrequency,
		LoanDate:             loanDate,
	}

	err = postgres.CreateLoan(loan)
	if err != nil {
		return nil, err
	}

	return &model.Loan{
		ContactID:            input.ContactID,
		LoanReference:        input.LoanReference,
		LoanType:             input.LoanType,
		InterestType:         input.InterestType,
		PrincipalAmount:      input.PrincipalAmount,
		OutstandingPrincipal: input.OutstandingPrincipal,
		InterestRate:         input.InterestRate,
	}, nil
}

// CreatePayment is the resolver for the createPayment field.
func (r *mutationResolver) CreatePayment(ctx context.Context, input model.NewPayment) (*model.Payment, error) {
	paymentDate, err := time.Parse("2006-01-02", input.PaymentDate)
	if err != nil {
		return nil, err
	}
	paymentMethod := ""
	if input.PaymentMethod != nil {
		paymentMethod = *input.PaymentMethod
	}

	transactionReference := ""
	if input.TransactionReference != nil {
		transactionReference = *input.TransactionReference
	}

	notes := ""
	if input.Notes != nil {
		notes = *input.Notes
	}
	payment := entities.Payment{
		LoanID:               int(input.LoanID),
		PaymentDate:          paymentDate,
		PaymentAmount:        input.PaymentAmount,
		PaymentType:          input.PaymentType,
		PaymentMethod:        paymentMethod,
		TransactionReference: transactionReference,
		Notes:                notes,
	}
	err = postgres.CreatePayment(payment)
	if err != nil {
		return nil, err
	}

	return &model.Payment{
		LoanID:               input.LoanID,
		PaymentDate:          input.PaymentDate,
		PaymentAmount:        input.PaymentAmount,
		PaymentType:          input.PaymentType,
		PaymentMethod:        input.PaymentMethod,
		TransactionReference: input.TransactionReference,
		Notes:                input.Notes,
	}, nil
}

// Loans is the resolver for the loans field.
func (r *queryResolver) Loans(ctx context.Context) ([]*model.Loan, error) {
	loans, err := postgres.GetAllLoans()
	if err != nil {
		return nil, err
	}

	var result []*model.Loan

	for _, loan := range loans {

		result = append(result, &model.Loan{
			ID:                   strconv.Itoa(loan.ID),
			ContactID:            int32(loan.ContactID),
			LoanReference:        loan.LoanReference,
			LoanType:             loan.LoanType,
			InterestType:         loan.InterestType,
			PrincipalAmount:      loan.PrincipalAmount,
			OutstandingPrincipal: loan.OutstandingPrincipal,
			InterestRate:         loan.InterestRate,
		})
	}

	return result, nil
}

// Loan is the resolver for the loan field based on iD
func (r *queryResolver) Loan(ctx context.Context, id string) (*model.Loan, error) {
	loanID, err := strconv.Atoi(id)
	if err != nil {
		return nil, err
	}

	loan, err := postgres.GetLoanByID(loanID)
	if err != nil {
		return nil, err
	}

	return &model.Loan{
		ID:                   strconv.Itoa(loan.ID),
		ContactID:            int32(loan.ContactID),
		LoanReference:        loan.LoanReference,
		LoanType:             loan.LoanType,
		InterestType:         loan.InterestType,
		PrincipalAmount:      loan.PrincipalAmount,
		OutstandingPrincipal: loan.OutstandingPrincipal,
		InterestRate:         loan.InterestRate,
	}, nil
}

// PaymentsByLoan is the resolver for the paymentsByLoan field.
func (r *queryResolver) PaymentsByLoan(ctx context.Context, loanID int32) ([]*model.Payment, error) {

	payments, err := postgres.GetPaymentsByLoanID(int(loanID))
	if err != nil {
		return nil, err
	}

	var result []*model.Payment

	for _, payment := range payments {

		paymentDate := payment.PaymentDate.Format("2006-01-02")

		result = append(result, &model.Payment{
			ID:                   strconv.Itoa(payment.ID),
			LoanID:               int32(payment.LoanID),
			PaymentDate:          paymentDate,
			PaymentAmount:        payment.PaymentAmount,
			PaymentType:          payment.PaymentType,
			PaymentMethod:        &payment.PaymentMethod,
			TransactionReference: &payment.TransactionReference,
			Notes:                &payment.Notes,
		})
	}

	return result, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
