package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"
	"errors"
	"finance-tracker/backend/entities"
	"finance-tracker/backend/graph/model"
	"finance-tracker/backend/helper"
	"finance-tracker/backend/postgres"
	"finance-tracker/backend/service"
	"strconv"
	"time"
)

// CreateLoan is the resolver for the createLoan field.
func (r *mutationResolver) CreateLoan(ctx context.Context, input model.NewLoan) (*model.Loan, error) {
	loanDate, err := time.Parse("2006-01-02", input.LoanDate)
	if err != nil {
		return nil, err
	}

	dueDay := 0
	if input.DueDay != nil {
		dueDay = int(*input.DueDay)
	}

	hasSecurity := false
	if input.HasSecurity != nil {
		hasSecurity = *input.HasSecurity
	}

	notes := ""
	if input.Notes != nil {
		notes = *input.Notes
	}
	contact, err := postgres.GetContactByID(int(input.ContactID))
	if err != nil {
		return nil, err
	}

	if contact.Status != "ACTIVE" {
		return nil, errors.New("cannot create loan for an inactive contact")
	}

	loan := entities.Loan{
		ContactID:            int(input.ContactID),
		LoanReference:        "",
		LoanType:             input.LoanType,
		InterestType:         input.InterestType,
		PrincipalAmount:      input.PrincipalAmount,
		OutstandingPrincipal: input.PrincipalAmount,
		InterestRate:         input.InterestRate,
		InterestFrequency:    input.InterestFrequency,
		LoanDate:             loanDate,
		DueDay:               dueDay,
		LoanTenure:           int(input.LoanTenure),
		TenureUnit:           input.TenureUnit,
		HasSecurity:          hasSecurity,
		Status:               "ACTIVE",
		Notes:                notes,
	}

	err = postgres.CreateLoan(&loan)
	if err != nil {
		return nil, err
	}

	// Generate Loan Reference
	loan.LoanReference = helper.GenerateLoanReference(loan.ID)

	// Update Loan Reference
	err = postgres.UpdateLoanReference(loan.ID, loan.LoanReference)
	if err != nil {
		return nil, err
	}

	return &model.Loan{
		ID:                   strconv.Itoa(loan.ID),
		ContactID:            input.ContactID,
		LoanReference:        loan.LoanReference,
		LoanType:             loan.LoanType,
		InterestType:         loan.InterestType,
		PrincipalAmount:      loan.PrincipalAmount,
		OutstandingPrincipal: loan.OutstandingPrincipal,
		InterestRate:         loan.InterestRate,
		InterestFrequency:    loan.InterestFrequency,
		LoanDate:             input.LoanDate,
		DueDay:               input.DueDay,
		LoanTenure:           input.LoanTenure,
		TenureUnit:           loan.TenureUnit,
		HasSecurity:          loan.HasSecurity,
		Status:               loan.Status,
		Notes:                input.Notes,
	}, nil
}

// CreatePayment is the resolver for the createPayment field.
func (r *mutationResolver) CreatePayment(ctx context.Context, input model.NewPayment) (*model.Payment, error) {
	paymentDate, err := time.Parse("2006-01-02", input.PaymentDate)
	if err != nil {
		return nil, err
	}
	paymentMethod := ""
	if input.PaymentMethod != nil {
		paymentMethod = *input.PaymentMethod
	}

	transactionReference := ""
	if input.TransactionReference != nil {
		transactionReference = *input.TransactionReference
	}

	notes := ""
	if input.Notes != nil {
		notes = *input.Notes
	}
	payment := entities.Payment{
		LoanID:               int(input.LoanID),
		PaymentDate:          paymentDate,
		PaymentAmount:        input.PaymentAmount,
		PaymentType:          input.PaymentType,
		PaymentMethod:        paymentMethod,
		TransactionReference: transactionReference,
		Notes:                notes,
	}
	payment, err = postgres.CreatePayment(payment)
	if err != nil {
		return nil, err
	}

	return &model.Payment{
		ID:                   strconv.Itoa(payment.ID),
		LoanID:               int32(payment.LoanID),
		PaymentDate:          payment.PaymentDate.Format("2006-01-02"),
		PaymentAmount:        payment.PaymentAmount,
		PaymentType:          payment.PaymentType,
		PaymentMethod:        &payment.PaymentMethod,
		TransactionReference: &payment.TransactionReference,
		Notes:                &payment.Notes,
	}, nil
}

// UpdatePayment is the resolver for the updatePayment field.
func (r *mutationResolver) UpdatePayment(ctx context.Context, id string, input model.NewPayment) (*model.Payment, error) {
	paymentID, err := strconv.Atoi(id)
	if err != nil {
		return nil, err
	}

	paymentDate, err := time.Parse("2006-01-02", input.PaymentDate)
	if err != nil {
		return nil, err
	}

	paymentMethod := ""
	if input.PaymentMethod != nil {
		paymentMethod = *input.PaymentMethod
	}

	transactionReference := ""
	if input.TransactionReference != nil {
		transactionReference = *input.TransactionReference
	}

	notes := ""
	if input.Notes != nil {
		notes = *input.Notes
	}

	payment := entities.Payment{
		LoanID:               int(input.LoanID),
		PaymentDate:          paymentDate,
		PaymentAmount:        input.PaymentAmount,
		PaymentType:          input.PaymentType,
		PaymentMethod:        paymentMethod,
		TransactionReference: transactionReference,
		Notes:                notes,
	}

	err = postgres.UpdatePayment(paymentID, payment)
	if err != nil {
		return nil, err
	}

	return &model.Payment{
		ID:                   id,
		LoanID:               input.LoanID,
		PaymentDate:          input.PaymentDate,
		PaymentAmount:        input.PaymentAmount,
		PaymentType:          input.PaymentType,
		PaymentMethod:        input.PaymentMethod,
		TransactionReference: input.TransactionReference,
		Notes:                input.Notes,
	}, nil
}

// DeletePayment is the resolver for the deletePayment field.
func (r *mutationResolver) DeletePayment(ctx context.Context, id string) (bool, error) {
	paymentID, err := strconv.Atoi(id)
	if err != nil {
		return false, err
	}

	err = postgres.DeletePayment(paymentID)
	if err != nil {
		return false, err
	}

	return true, nil
}

// CreateContact is the resolver for the createContact field.
func (r *mutationResolver) CreateContact(ctx context.Context, input model.NewContact) (*model.Contact, error) {
	phoneNumber := ""
	if input.PhoneNumber != nil {
		phoneNumber = *input.PhoneNumber
	}

	email := ""
	if input.Email != nil {
		email = *input.Email
	}

	address := ""
	if input.Address != nil {
		address = *input.Address
	}

	occupation := ""
	if input.Occupation != nil {
		occupation = *input.Occupation
	}

	contactType := "PERSON"
	if input.ContactType != nil {
		contactType = *input.ContactType
	}

	notes := ""
	if input.Notes != nil {
		notes = *input.Notes
	}

	contact := entities.Contact{
		ContactCode: "",
		FullName:    input.FullName,
		PhoneNumber: phoneNumber,
		Email:       email,
		Address:     address,
		Occupation:  occupation,
		ContactType: contactType,
		Notes:       notes,
		Status:      "ACTIVE",
	}

	err := postgres.CreateContact(&contact)
	if err != nil {
		return nil, err
	}

	// Generate Contact Code
	contact.ContactCode = helper.GenerateContactCode(contact.ID)

	// Update Contact Code in DB
	err = postgres.UpdateContactCode(contact.ID, contact.ContactCode)
	if err != nil {
		return nil, err
	}

	return &model.Contact{
		ID:          strconv.Itoa(contact.ID),
		ContactCode: contact.ContactCode,
		FullName:    contact.FullName,
		PhoneNumber: &contact.PhoneNumber,
		Email:       &contact.Email,
		Address:     &contact.Address,
		Occupation:  &contact.Occupation,
		ContactType: contact.ContactType,
		Notes:       &contact.Notes,
		Status:      contact.Status,
	}, nil
}

// UpdateContact is the resolver for the updateContact field.
func (r *mutationResolver) UpdateContact(ctx context.Context, id int32, input model.UpdateContact) (*model.Contact, error) {
	phoneNumber := ""
	if input.PhoneNumber != nil {
		phoneNumber = *input.PhoneNumber
	}

	email := ""
	if input.Email != nil {
		email = *input.Email
	}

	address := ""
	if input.Address != nil {
		address = *input.Address
	}

	occupation := ""
	if input.Occupation != nil {
		occupation = *input.Occupation
	}

	contactType := "PERSON"
	if input.ContactType != nil {
		contactType = *input.ContactType
	}

	notes := ""
	if input.Notes != nil {
		notes = *input.Notes
	}

	contact := entities.Contact{
		FullName:    input.FullName,
		PhoneNumber: phoneNumber,
		Email:       email,
		Address:     address,
		Occupation:  occupation,
		ContactType: contactType,
		Notes:       notes,
	}

	err := postgres.UpdateContact(int(id), contact)
	if err != nil {
		return nil, err
	}

	updatedContact, err := postgres.GetContactByID(int(id))
	if err != nil {
		return nil, err
	}

	return &model.Contact{
		ID:          strconv.Itoa(updatedContact.ID),
		ContactCode: updatedContact.ContactCode,
		FullName:    updatedContact.FullName,
		PhoneNumber: &updatedContact.PhoneNumber,
		Email:       &updatedContact.Email,
		Address:     &updatedContact.Address,
		Occupation:  &updatedContact.Occupation,
		ContactType: updatedContact.ContactType,
		Notes:       &updatedContact.Notes,
		Status:      updatedContact.Status,
		CreatedAt:   updatedContact.CreatedAt.Format("2006-01-02 15:04:05"),
		UpdatedAt:   updatedContact.UpdatedAt.Format("2006-01-02 15:04:05"),
	}, nil
}

// ChangeContactStatus is the resolver for the changeContactStatus field.
func (r *mutationResolver) ChangeContactStatus(ctx context.Context, input model.ChangeContactStatusInput) (*model.Contact, error) {
	// Don't allow deactivation if active loans exist
	if input.Status == "INACTIVE" {

		hasActiveLoans, err := postgres.HasActiveLoans(int(input.ID))
		if err != nil {
			return nil, err
		}

		if hasActiveLoans {
			return nil, errors.New("cannot deactivate contact because active loans exist")
		}
	}

	err := postgres.ChangeContactStatus(int(input.ID), input.Status)
	if err != nil {
		return nil, err
	}

	contact, err := postgres.GetContactByID(int(input.ID))
	if err != nil {
		return nil, err
	}

	return &model.Contact{
		ID:          strconv.Itoa(contact.ID),
		ContactCode: contact.ContactCode,
		FullName:    contact.FullName,
		PhoneNumber: &contact.PhoneNumber,
		Email:       &contact.Email,
		Address:     &contact.Address,
		Occupation:  &contact.Occupation,
		ContactType: contact.ContactType,
		Notes:       &contact.Notes,
		Status:      contact.Status,
		CreatedAt:   contact.CreatedAt.Format("2006-01-02 15:04:05"),
		UpdatedAt:   contact.UpdatedAt.Format("2006-01-02 15:04:05"),
	}, nil
}

// UpdateLoan is the resolver for the updateLoan field.
func (r *mutationResolver) UpdateLoan(ctx context.Context, id int32, input model.UpdateLoan) (*model.Loan, error) {
	loanDate, err := time.Parse("2006-01-02", input.LoanDate)
	if err != nil {
		return nil, err
	}

	dueDay := 0
	if input.DueDay != nil {
		dueDay = int(*input.DueDay)
	}

	hasSecurity := false
	if input.HasSecurity != nil {
		hasSecurity = *input.HasSecurity
	}

	notes := ""
	if input.Notes != nil {
		notes = *input.Notes
	}

	loan := entities.Loan{
		InterestType:      input.InterestType,
		PrincipalAmount:   input.PrincipalAmount,
		InterestRate:      input.InterestRate,
		InterestFrequency: input.InterestFrequency,
		LoanDate:          loanDate,
		DueDay:            dueDay,
		LoanTenure:        int(input.LoanTenure),
		TenureUnit:        input.TenureUnit,
		HasSecurity:       hasSecurity,
		Notes:             notes,
	}
	hasPayments, err := postgres.HasPayments(int(id))
	if err != nil {
		return nil, err
	}

	if hasPayments {
		return nil, errors.New("cannot update loan after payments have been recorded")
	}
	err = postgres.UpdateLoan(int(id), loan)
	if err != nil {
		return nil, err
	}

	updatedLoan, err := postgres.GetLoanByID(int(id))
	if err != nil {
		return nil, err
	}

	return &model.Loan{
		ID:                   strconv.Itoa(updatedLoan.ID),
		ContactID:            int32(updatedLoan.ContactID),
		LoanReference:        updatedLoan.LoanReference,
		LoanType:             updatedLoan.LoanType,
		InterestType:         updatedLoan.InterestType,
		PrincipalAmount:      updatedLoan.PrincipalAmount,
		OutstandingPrincipal: updatedLoan.OutstandingPrincipal,
		InterestRate:         updatedLoan.InterestRate,
		InterestFrequency:    updatedLoan.InterestFrequency,
		LoanDate:             updatedLoan.LoanDate.Format("2006-01-02"),
		DueDay:               input.DueDay,
		LoanTenure:           int32(updatedLoan.LoanTenure),
		TenureUnit:           updatedLoan.TenureUnit,
		HasSecurity:          updatedLoan.HasSecurity,
		Status:               updatedLoan.Status,
		Notes:                &updatedLoan.Notes,
		CreatedAt:            updatedLoan.CreatedAt.Format("2006-01-02 15:04:05"),
		UpdatedAt:            updatedLoan.UpdatedAt.Format("2006-01-02 15:04:05"),
	}, nil
}

// ChangeLoanStatus is the resolver for the changeLoanStatus field.
func (r *mutationResolver) ChangeLoanStatus(ctx context.Context, input model.ChangeLoanStatusInput) (*model.Loan, error) {

	loan, err := postgres.GetLoanByID(int(input.ID))
	if err != nil {
		return nil, err
	}

	// Cannot reopen a closed loan
	if loan.Status == "CLOSED" {
		return nil, errors.New("closed loans cannot be reopened")
	}

	// Cannot close if outstanding principal exists
	if input.Status == "CLOSED" && loan.OutstandingPrincipal > 0 {
		return nil, errors.New("cannot close the loan because there is still an outstanding balance")
	}

	err = postgres.ChangeLoanStatus(int(input.ID), input.Status)
	if err != nil {
		return nil, err
	}

	updatedLoan, err := postgres.GetLoanByID(int(input.ID))
	if err != nil {
		return nil, err
	}

	var dueDay *int32
	if updatedLoan.DueDay != 0 {
		d := int32(updatedLoan.DueDay)
		dueDay = &d
	}

	var notes *string
	if updatedLoan.Notes != "" {
		n := updatedLoan.Notes
		notes = &n
	}

	return &model.Loan{
		ID:                   strconv.Itoa(updatedLoan.ID),
		ContactID:            int32(updatedLoan.ContactID),
		ContactCode:          updatedLoan.ContactCode,
		ContactName:          updatedLoan.ContactName,
		LoanReference:        updatedLoan.LoanReference,
		LoanType:             updatedLoan.LoanType,
		InterestType:         updatedLoan.InterestType,
		PrincipalAmount:      updatedLoan.PrincipalAmount,
		OutstandingPrincipal: updatedLoan.OutstandingPrincipal,
		InterestRate:         updatedLoan.InterestRate,
		InterestFrequency:    updatedLoan.InterestFrequency,
		LoanDate:             updatedLoan.LoanDate.Format("2006-01-02"),
		DueDay:               dueDay,
		LoanTenure:           int32(updatedLoan.LoanTenure),
		TenureUnit:           updatedLoan.TenureUnit,
		HasSecurity:          updatedLoan.HasSecurity,
		Status:               updatedLoan.Status,
		Notes:                notes,
		CreatedAt:            updatedLoan.CreatedAt.Format("2006-01-02 15:04:05"),
		UpdatedAt:            updatedLoan.UpdatedAt.Format("2006-01-02 15:04:05"),
	}, nil
}

// Loans is the resolver for the loans field.
func (r *queryResolver) Loans(ctx context.Context) ([]*model.Loan, error) {
	loans, err := postgres.GetAllLoans()
	if err != nil {
		return nil, err
	}

	var result []*model.Loan

	for _, loan := range loans {

		result = append(result, &model.Loan{
			ID:                   strconv.Itoa(loan.ID),
			ContactID:            int32(loan.ContactID),
			ContactCode:          loan.ContactCode,
			ContactName:          loan.ContactName,
			LoanReference:        loan.LoanReference,
			LoanType:             loan.LoanType,
			InterestType:         loan.InterestType,
			PrincipalAmount:      loan.PrincipalAmount,
			OutstandingPrincipal: loan.OutstandingPrincipal,
			InterestRate:         loan.InterestRate,
			InterestFrequency:    loan.InterestFrequency,
			LoanDate:             loan.LoanDate.Format("2006-01-02"),
			DueDay: func() *int32 {
				v := int32(loan.DueDay)
				return &v
			}(),
			LoanTenure:  int32(loan.LoanTenure),
			TenureUnit:  loan.TenureUnit,
			HasSecurity: loan.HasSecurity,
			Status:      loan.Status,
			Notes:       &loan.Notes,
			CreatedAt:   loan.CreatedAt.Format("2006-01-02 15:04:05"),
			UpdatedAt:   loan.UpdatedAt.Format("2006-01-02 15:04:05"),
		})
	}

	return result, nil
}

// Loan is the resolver for the loan field based on iD
func (r *queryResolver) Loan(ctx context.Context, id string) (*model.Loan, error) {
	loanID, err := strconv.Atoi(id)
	if err != nil {
		return nil, err
	}

	loan, err := postgres.GetLoanByID(loanID)
	if err != nil {
		return nil, err
	}

	var dueDay *int32
	if loan.DueDay != 0 {
		v := int32(loan.DueDay)
		dueDay = &v
	}

	return &model.Loan{
		ID:                   strconv.Itoa(loan.ID),
		ContactID:            int32(loan.ContactID),
		ContactCode:          loan.ContactCode,
		ContactName:          loan.ContactName,
		LoanReference:        loan.LoanReference,
		LoanType:             loan.LoanType,
		InterestType:         loan.InterestType,
		PrincipalAmount:      loan.PrincipalAmount,
		OutstandingPrincipal: loan.OutstandingPrincipal,
		InterestRate:         loan.InterestRate,
		InterestFrequency:    loan.InterestFrequency,
		LoanDate:             loan.LoanDate.Format("2006-01-02"),
		DueDay:               dueDay,
		LoanTenure:           int32(loan.LoanTenure),
		TenureUnit:           loan.TenureUnit,
		HasSecurity:          loan.HasSecurity,
		Status:               loan.Status,
		Notes:                &loan.Notes,
		CreatedAt:            loan.CreatedAt.Format("2006-01-02 15:04:05"),
		UpdatedAt:            loan.UpdatedAt.Format("2006-01-02 15:04:05"),
	}, nil
}

// PaymentsByLoan is the resolver for the paymentsByLoan field.
func (r *queryResolver) PaymentsByLoan(ctx context.Context, loanID int32) ([]*model.Payment, error) {
	payments, err := postgres.GetPaymentsByLoanID(int(loanID))
	if err != nil {
		return nil, err
	}

	var result []*model.Payment

	for _, payment := range payments {

		paymentDate := payment.PaymentDate.Format("2006-01-02")

		result = append(result, &model.Payment{
			ID:                   strconv.Itoa(payment.ID),
			LoanID:               int32(payment.LoanID),
			PaymentDate:          paymentDate,
			PaymentAmount:        payment.PaymentAmount,
			PaymentType:          payment.PaymentType,
			PaymentMethod:        &payment.PaymentMethod,
			TransactionReference: &payment.TransactionReference,
			Notes:                &payment.Notes,
		})
	}

	return result, nil
}

// LoanSummary is the resolver for the loanSummary field.
func (r *queryResolver) LoanSummary(ctx context.Context, id string) (*model.LoanSummary, error) {
	loanID, err := strconv.Atoi(id)
	if err != nil {
		return nil, err
	}
	loan, err := postgres.GetLoanByID(loanID)
	if err != nil {
		return nil, err
	}

	payments, err := postgres.GetPaymentsByLoanID(loanID)
	if err != nil {
		return nil, err
	}

	summary := service.GenerateLoanSummary(loan, payments)

	return &model.LoanSummary{
		Loan: &model.Loan{
			ID:                   strconv.Itoa(summary.Loan.ID),
			ContactID:            int32(summary.Loan.ContactID),
			LoanReference:        summary.Loan.LoanReference,
			LoanType:             summary.Loan.LoanType,
			InterestType:         summary.Loan.InterestType,
			PrincipalAmount:      summary.Loan.PrincipalAmount,
			OutstandingPrincipal: summary.Loan.OutstandingPrincipal,
			InterestRate:         summary.Loan.InterestRate,
		},
		PrincipalPaid: summary.PrincipalPaid,
		Outstanding:   summary.Outstanding,
		InterestPaid:  summary.InterestPaid,
		Status:        summary.Status,
	}, nil
}

// DashboardSummary is the resolver for the dashboardSummary field.
func (r *queryResolver) DashboardSummary(ctx context.Context) (*model.DashboardSummary, error) {
	summary, err := service.GenerateDashboardSummary()
	if err != nil {
		return nil, err
	}

	return &model.DashboardSummary{
		TotalLent:            summary.TotalLent,
		TotalBorrowed:        summary.TotalBorrowed,
		OutstandingToReceive: summary.OutstandingToReceive,
		OutstandingToPay:     summary.OutstandingToPay,
		InterestEarned:       summary.InterestEarned,
		InterestPaid:         summary.InterestPaid,
		NetInterest:          summary.NetInterest,
		NetAssets:            summary.NetAssets,
		NetWorth:             summary.NetWorth,
		ActiveLoans:          int32(summary.ActiveLoans),
		ClosedLoans:          int32(summary.ClosedLoans),
	}, nil
}

// LoanLedger is the resolver for the loanLedger field.
func (r *queryResolver) LoanLedger(ctx context.Context, id string) ([]*model.LedgerEntry, error) {
	loanID, err := strconv.Atoi(id)
	if err != nil {
		return nil, err
	}
	loan, err := postgres.GetLoanByID(loanID)
	if err != nil {
		return nil, err
	}
	payments, err := postgres.GetPaymentsByLoanID(loanID)
	if err != nil {
		return nil, err
	}

	ledger := service.GenerateLoanLedger(loan, payments)

	var result []*model.LedgerEntry

	for _, entry := range ledger {
		result = append(result, &model.LedgerEntry{
			PaymentDate:   entry.PaymentDate,
			PaymentAmount: entry.PaymentAmount,
			PrincipalPaid: entry.PrincipalPaid,
			InterestPaid:  entry.InterestPaid,
			Outstanding:   entry.Outstanding,
			Description:   entry.Description,
		})
	}

	return result, nil
}

// ContactSummary is the resolver for the contactSummary field.
func (r *queryResolver) ContactSummary(ctx context.Context, contactID int32) (*model.ContactSummary, error) {
	summary, err := service.GenerateContactSummary(int(contactID))
	if err != nil {
		return nil, err
	}

	var loanSummaries []*model.LoanSummary

	for _, loan := range summary.Loans {

		loanSummaries = append(loanSummaries, &model.LoanSummary{
			Loan: &model.Loan{
				ID:                   strconv.Itoa(loan.Loan.ID),
				ContactID:            int32(loan.Loan.ContactID),
				LoanReference:        loan.Loan.LoanReference,
				LoanType:             loan.Loan.LoanType,
				InterestType:         loan.Loan.InterestType,
				PrincipalAmount:      loan.Loan.PrincipalAmount,
				OutstandingPrincipal: loan.Loan.OutstandingPrincipal,
				InterestRate:         loan.Loan.InterestRate,
			},
			PrincipalPaid: loan.PrincipalPaid,
			InterestPaid:  loan.InterestPaid,
			Outstanding:   loan.Outstanding,
			Status:        loan.Status,
		})
	}

	return &model.ContactSummary{
		ContactID:      int32(summary.ContactID),
		TotalLent:      summary.TotalLent,
		TotalBorrowed:  summary.TotalBorrowed,
		Outstanding:    summary.Outstanding,
		ActiveLoans:    int32(summary.ActiveLoans),
		ClosedLoans:    int32(summary.ClosedLoans),
		InterestEarned: summary.InterestEarned,
		InterestPaid:   summary.InterestPaid,
		Loans:          loanSummaries,
	}, nil
}

// MonthlyCashFlow is the resolver for the monthlyCashFlow field.
func (r *queryResolver) MonthlyCashFlow(ctx context.Context, year int32, month int32) (*model.MonthlyCashFlow, error) {
	cashFlow, err := service.GenerateMonthlyCashFlow(int(year), int(month))
	if err != nil {
		return nil, err
	}

	return &model.MonthlyCashFlow{
		Year:              int32(cashFlow.Year),
		Month:             int32(cashFlow.Month),
		TotalReceived:     cashFlow.TotalReceived,
		TotalPaid:         cashFlow.TotalPaid,
		PrincipalReceived: cashFlow.PrincipalReceived,
		InterestReceived:  cashFlow.InterestReceived,
		PrincipalPaid:     cashFlow.PrincipalPaid,
		InterestPaid:      cashFlow.InterestPaid,
		NetCashFlow:       cashFlow.NetCashFlow,
	}, nil
}

// Contacts is the resolver for the contacts field.
func (r *queryResolver) Contacts(ctx context.Context) ([]*model.Contact, error) {
	contacts, err := postgres.GetAllContacts()
	if err != nil {
		return nil, err
	}

	var result []*model.Contact

	for _, contact := range contacts {

		result = append(result, &model.Contact{
			ID:          strconv.Itoa(contact.ID),
			ContactCode: contact.ContactCode,
			FullName:    contact.FullName,
			PhoneNumber: &contact.PhoneNumber,
			Email:       &contact.Email,
			Address:     &contact.Address,
			Occupation:  &contact.Occupation,
			ContactType: contact.ContactType,
			Notes:       &contact.Notes,
			Status:      contact.Status,
			CreatedAt:   contact.CreatedAt.Format("2006-01-02 15:04:05"),
			UpdatedAt:   contact.UpdatedAt.Format("2006-01-02 15:04:05"),
		})
	}

	return result, nil
}

// Contact is the resolver for the contact field.
func (r *queryResolver) Contact(ctx context.Context, id int32) (*model.Contact, error) {
	contact, err := postgres.GetContactByID(int(id))
	if err != nil {
		return nil, err
	}

	return &model.Contact{
		ID:          strconv.Itoa(contact.ID),
		ContactCode: contact.ContactCode,
		FullName:    contact.FullName,
		PhoneNumber: &contact.PhoneNumber,
		Email:       &contact.Email,
		Address:     &contact.Address,
		Occupation:  &contact.Occupation,
		ContactType: contact.ContactType,
		Notes:       &contact.Notes,
		Status:      contact.Status,
		CreatedAt:   contact.CreatedAt.Format("2006-01-02 15:04:05"),
		UpdatedAt:   contact.UpdatedAt.Format("2006-01-02 15:04:05"),
	}, nil
}

// LoansByContact is the resolver for the loansByContact field.
func (r *queryResolver) LoansByContact(ctx context.Context, contactID int32) ([]*model.Loan, error) {
	loans, err := postgres.GetLoansByContactID(int(contactID))
	if err != nil {
		return nil, err
	}

	var result []*model.Loan

	for _, loan := range loans {

		var dueDay *int32
		if loan.DueDay != 0 {
			d := int32(loan.DueDay)
			dueDay = &d
		}

		var notes *string
		if loan.Notes != "" {
			n := loan.Notes
			notes = &n
		}

		result = append(result, &model.Loan{
			ID:                   strconv.Itoa(loan.ID),
			ContactID:            int32(loan.ContactID),
			ContactCode:          loan.ContactCode,
			ContactName:          loan.ContactName,
			LoanReference:        loan.LoanReference,
			LoanType:             loan.LoanType,
			InterestType:         loan.InterestType,
			PrincipalAmount:      loan.PrincipalAmount,
			OutstandingPrincipal: loan.OutstandingPrincipal,
			InterestRate:         loan.InterestRate,
			InterestFrequency:    loan.InterestFrequency,
			LoanDate:             loan.LoanDate.Format("2006-01-02"),
			DueDay:               dueDay,
			LoanTenure:           int32(loan.LoanTenure),
			TenureUnit:           loan.TenureUnit,
			HasSecurity:          loan.HasSecurity,
			Status:               loan.Status,
			Notes:                notes,
			CreatedAt:            loan.CreatedAt.Format("2006-01-02 15:04:05"),
			UpdatedAt:            loan.UpdatedAt.Format("2006-01-02 15:04:05"),
		})
	}

	return result, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
