package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"
	"strconv"

	"finance-tracker/backend/graph/model"
	"finance-tracker/backend/postgres"
)

// Loans is the resolver for the loans field.
func (r *queryResolver) Loans(ctx context.Context) ([]*model.Loan, error) {

	loans, err := postgres.GetAllLoans()
	if err != nil {
		return nil, err
	}

	var result []*model.Loan

	for _, loan := range loans {

		result = append(result, &model.Loan{
			ID:                   strconv.Itoa(loan.ID),
			ContactID:            int32(loan.ContactID),
			LoanReference:        loan.LoanReference,
			LoanType:             loan.LoanType,
			InterestType:         loan.InterestType,
			PrincipalAmount:      loan.PrincipalAmount,
			OutstandingPrincipal: loan.OutstandingPrincipal,
			InterestRate:         loan.InterestRate,
		})
	}

	return result, nil
}
// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }
type mutationResolver struct{ *Resolver }
*/
